# -*- mode: ruby -*-
# vi: set ft=ruby :
#require 'berkshelf/vagrant'

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = '2'

Vagrant.require_version '>= 1.5.0'

Vagrant.configure("2") do |config|

end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  config.vm.hostname = 'web-berkshelf'


  if Vagrant.has_plugin?("vagrant-omnibus")
    config.omnibus.chef_version = 'latest'
  end


  config.vm.box = 'precise32'


  config.vm.network :private_network, type: 'dhcp'

  config.vm.define :web do |box|
    box.vm.network :forwarded_port, guest: 80, host: 8010
    box.vm.hostname = "web1"

    box.vm.provision :chef_solo do |chef|
      chef.run_list = [
        'recipe[web::default]'
      ]
    end
  end
  
  config.vm.define :web do |box|
    box.vm.network :forwarded_port, guest: 80, host: 8011
    box.vm.hostname = "web2"

    box.vm.provision :chef_solo do |chef|
      chef.run_list = [
        'recipe[web::default]'
      ]
    end
  end
  

end
